config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :client_feedbacks
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'home/index'
  root 'home#index'
  get '/work' => 'home#work'
  get '/insight' => 'home#insight'
  get '/solution' => 'home#solution'
  get '/company' => 'home#company'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client_feedback.rb
class ClientFeedback < ApplicationRecord

  mount_uploader :avatar, AvatarUploader
  scope :approved?, -> { where(approved: true) }

  after_create :send_mail_to_admin

  def full_name
    [try(:first_name).camelize, try(:last_name).camelize].compact.join(' ')
  end

  def city_state
    [try(:city).camelize, try(:state).camelize].compact.join(', ')
  end

  def send_mail_to_admin
    FeedbackMailer.send_feedback(self).deliver_now!
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/client_feedbacks_controller.rb
class ClientFeedbacksController < InheritedResources::Base
before_action :set_client_feedback, only: [:show, :edit, :update, :destroy]

  # GET /client_feedbacks
  # GET /client_feedbacks.json
  def index
    @client_feedbacks = ClientFeedback.approved?
  end

  # GET /client_feedbacks/1
  # GET /client_feedbacks/1.json
  def show
  end

  # GET /client_feedbacks/new
  def new
    @client_feedback = ClientFeedback.new
  end

  # GET /client_feedbacks/1/edit
  def edit
  end

  # POST /client_feedbacks
  # POST /client_feedbacks.json
  def create
    @client_feedback = ClientFeedback.new(client_feedback_params)

    respond_to do |format|
      if @client_feedback.save
        session[:create_sucess] = true
        format.html { redirect_to client_feedbacks_url, notice: 'Client feedback was successfully created.' }
        # format.json { render :show, status: :created, location: @client_feedback }
      else
        format.html { render :new }
        format.json { render json: @client_feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_feedbacks/1
  # PATCH/PUT /client_feedbacks/1.json
  def update
    respond_to do |format|
      if @client_feedback.update(client_feedback_params)
        format.html { redirect_to @client_feedback, notice: 'Client feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @client_feedback }
      else
        format.html { render :edit }
        format.json { render json: @client_feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_feedbacks/1
  # DELETE /client_feedbacks/1.json
  def destroy
    @client_feedback.destroy
    respond_to do |format|
      format.html { redirect_to client_feedbacks_url, notice: 'Client feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_client_feedback
    @client_feedback = ClientFeedback.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def client_feedback_params
    params.require(:client_feedback).permit(:first_name, :last_name, :email, :contact, :feedback, :avatar, :address, :city, :state, :country, :zipcode,:approved)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < InheritedResources::Base

  private

    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :phone, :email, :subject, :message, :country, :state)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def work
  end

  def insight
  end

  def solution
  end
  
  def company
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_feedbacks_helper.rb
module ClientFeedbacksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/client_feedbacks/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= form_for(client_feedback) do |f| %>
    <% if client_feedback.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(client_feedback.errors.count, "error") %> prohibited this client_feedback from being saved:</h2>

        <ul>
        <% client_feedback.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control",required: true %>
    </div>

    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control",required: true %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control",required: true %>
    </div>

    <div class="form-group">
      <%= f.label :contact %>
      <%= f.text_field :contact, class: "form-control",required: true %>
    </div>

    <div class="form-group">
      <%= f.label :feedback %>
      <%= f.text_area :feedback, class: "form-control",required: true %>
    </div>

    <div class="form-group">
      <%= f.label :avatar %>
      <%= f.file_field :avatar, class: "form-control",required: true %>
    </div>

    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: "form-control",required: true %>
    </div>

    <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: "form-control",required: true %>
    </div>

    <div class="form-group">
      <%= f.label :state %>
      <%= f.text_field :state, class: "form-control",required: true %>
    </div>

    <div class="form-group">
      <%= f.label :country %>
      <%= f.text_field :country, class: "form-control",required: true %>
    </div>

    <div class="form-group">
      <%= f.label :zipcode %>
      <%= f.text_field :zipcode, class: "form-control",required: true %>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/client_feedbacks/edit.html.erb
<h1>Editing Client Feedback</h1>

<%= render 'form', client_feedback: @client_feedback %>

<%= link_to 'Show', @client_feedback %> |
<%= link_to 'Back', client_feedbacks_path %>

app/views/client_feedbacks/index.html.erb
<%#= render "layouts/header" %>
<section class="client-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center client-cover" style="padding:173px;">
        <p id="notice"><%= notice %></p>
        <h1>Client Feedbacks</h1>
        <%= link_to 'New Client Feedback', new_client_feedback_path, class: "btn btn-primary" %>
      </div>
      <%#= render "index" %>
    </div>
  </div>
</section>

<div id="clientModel" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close client-close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Thank you for your feedback.</h4>
      </div>
      <div class="modal-body">
        <p><img src="../assets/slider/smile.jpg" style="width:100px;"></p>
        <!-- <p class="text-warning"><small>If you don't save, your changes will be lost.</small></p> -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default client-close" data-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>

app/views/client_feedbacks/new.html.erb
<h1>New Client Feedback</h1>

<%= render 'form', client_feedback: @client_feedback %>

<%= link_to 'Back', client_feedbacks_path %>

app/views/client_feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @client_feedback.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @client_feedback.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client_feedback.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @client_feedback.contact %>
</p>

<p>
  <strong>Feedback:</strong>
  <%= @client_feedback.feedback %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @client_feedback.avatar %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client_feedback.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @client_feedback.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @client_feedback.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @client_feedback.country %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @client_feedback.zipcode %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @client_feedback.approved %>
</p>

<%= link_to 'Edit', edit_client_feedback_path(@client_feedback) %> |
<%= link_to 'Back', client_feedbacks_path %>

app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.number_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Message</th>
      <th>Country</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= contact.subject %></td>
        <td><%= contact.message %></td>
        <td><%= contact.country %></td>
        <td><%= contact.state %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @contact.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<p>
  <strong>Country:</strong>
  <%= @contact.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @contact.state %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/solution.html.erb
<%= render :partial => 'shared/menu' %>
<div class="wrapper" data-loadmodule="PageTransitions">
    <main id="main-content" class="main-content" tabindex="-1">

        <section class="module solution-hero" data-visible="false">
            <div class="module-background"></div>
            <div class="module-content">
                <div class="hero-content">
                    <h1 class="headline isFirst">Transformation in the age of the customer.</h1>
                    <div class="subhead postmodern-divider isSecond">Everything we do is centered on the belief that, in a constantly changing market filled with the explosion of technology and data, customers have the power. A new way of doing business is now required. We call this customer obsessed business transformation and offer six solutions to get there.</div>
                </div>
            </div>
        </section>

        <section class="solution-sub-nav landing module" data-visible="false">
            <div class="module-background"></div>
            <div class="module-content">
                <div class="solution-sub-nav-content">
                    <ol class="sub-nav-container">
                        <li class="sub-nav-item" style="background-color: #d3cfc9;">
                            <a class="sub-nav-item-link" href="/solution/journey-driven-consulting">
                                <header class="sub-nav-item-header">
                                    <h2 class="sub-nav-item-headline">Journey-Driven Consulting</h2>
                                </header>
                                <ul class="summary-list">
                                    <li class="summary-item">Digital Transformation Strategy</li>
                                    <li class="summary-item">Customer Journey Consulting</li>
                                    <li class="summary-item">Structured Innovation</li>
                                    <li class="summary-item">Strategic Prioritization & Roadmapping</li>
                                </ul>
                            </a>
                        </li>
                        <li class="sub-nav-item" style="background-color: #82c2ce;">
                            <a class="sub-nav-item-link" href="/solution/active-marketing">
                                <header class="sub-nav-item-header">
                                    <h2 class="sub-nav-item-headline">Active Marketing</h2>
                                </header>
                                <ul class="summary-list">
                                    <li class="summary-item">Strategic Program Planning</li>
                                    <li class="summary-item">Creative Concepting & Design</li>
                                    <li class="summary-item">Social & Content Marketing</li>
                                    <li class="summary-item">Precision Marketing & Media</li>
                                </ul>
                            </a>
                        </li>
                        <li class="sub-nav-item" style="background-color: #ffc877;">
                            <a class="sub-nav-item-link" href="/solution/experience-innovation">
                                <header class="sub-nav-item-header">
                                    <h2 class="sub-nav-item-headline">Experience Innovation</h2>
                                </header>
                                <ul class="summary-list">
                                    <li class="summary-item">Customer Experience Strategy</li>
                                    <li class="summary-item">Experience Design</li>
                                    <li class="summary-item">Product Development</li>
                                    <li class="summary-item">Emerging Experiences&trade;</li>
                                </ul>
                            </a>
                        </li>
                        <li class="sub-nav-item" style="background-color: #4f4848;">
                            <a class="sub-nav-item-link" href="/solution/intelligent-platforms">
                                <header class="sub-nav-item-header">
                                    <h2 class="sub-nav-item-headline">Intelligent Platforms</h2>
                                </header>
                                <ul class="summary-list">
                                    <li class="summary-item">Platform Strategy & Assessment</li>
                                    <li class="summary-item">Platform Build & Implementation</li>
                                    <li class="summary-item">Cognitive & Predictive Analytics</li>
                                    <li class="summary-item">Cloud Services</li>
                                </ul>
                            </a>
                        </li>
                        <li class="sub-nav-item" style="background-color: #c6db81;">
                            <a class="sub-nav-item-link" href="/solution/engagement-based-loyalty">
                                <header class="sub-nav-item-header">
                                    <h2 class="sub-nav-item-headline">Engagement-&#8203;Based Loyalty</h2>
                                </header>
                                <ul class="summary-list">
                                    <li class="summary-item">CRM</li>
                                    <li class="summary-item">Segmentation</li>
                                    <li class="summary-item">Loyalty Programs</li>
                                    <li class="summary-item">Marketing Automation</li>
                                </ul>
                            </a>
                        </li>
                        <li class="sub-nav-item" style="background-color: #ff6263;">
                            <a class="sub-nav-item-link" href="/solution/ubiquitous-commerce">
                                <header class="sub-nav-item-header">
                                    <h2 class="sub-nav-item-headline">Ubiquitous Commerce</h2>
                                </header>
                                <ul class="summary-list">
                                    <li class="summary-item">Commerce Strategy</li>
                                    <li class="summary-item">Rapid Commerce</li>
                                    <li class="summary-item">Ecommerce & CMS Platforms</li>
                                    <li class="summary-item">Sales & Customer Care</li>
                                </ul>
                            </a>
                        </li>
                    </ol>
                </div>
            </div>
        </section>
        <section class="module solution-contact" data-visible="false">
            <div class="module-background"></div>
            <div class="module-content">
                <div class="solution-contact-content">
                    <h2 class="headline">Here for tomorrow.</h2>
                    <div class="subhead">Motivated and inspired by what's next, we help our clients navigate the unknown, drive change and transform business.</div>
                    <div class="solution-contact-cta-container">
                        <a class="solution-contact-cta cta" href="/contact">Put our expertise to work for you.</a>
                    </div>
                </div>
            </div>
        </section>

    </main>
</div>

<%= render :partial => 'shared/footer' %>    
<script src="/assets/app.js"></script>
<script src="/assets/shared.js"></script>

app/views/shared/_footer.html.erb
<footer class="site-info" role="contentinfo">
  <div class="footer-content">
    <a href="index.html">
      <svg class="razorfish-logo" title="Razorfish" viewBox="0 0 146 26" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <use xlink:href="#site-logo"></use>
      </svg>
    </a>
    <div class="site-details">
      <ul class="site-social-links" data-visible="false">
        <li class="share-icon-container">
          <a href="https://www.linkedin.com/company/sapientrazorfish" class="icon-linkedin share-icon" target="_blank"><span>LinkedIn</span></a>
        </li>
        <li class="share-icon-container">
          <a href="https://twitter.com/sr_" class="icon-twitter share-icon" target="_blank"><span>Twitter</span></a>
        </li>
        <li class="share-icon-container">
          <a href="https://www.facebook.com/SapientRazorfish/" class="icon-facebook share-icon" target="_blank"><span>Facebook</span></a>
        </li>
      </ul>
      <ul class="site-legal">
        <li class="copyright">©2016 Razorfish All rights reserved</li>
        <li class="legal-link">
                <a href="general/terms" class="link muted">Terms</a>
        </li>
        <li class="legal-link">
                <a href="general/privacy" class="link muted">Privacy</a>
        </li>
        <li class="legal-link">
                <a href="general/sitemap" class="link muted">Site Map</a>
        </li>
        <li class="legal-link">
                <a href="general/accessibility" class="link muted">Accessibility</a>
        </li>
      </ul>
    </div>
  </div>
</footer>
<input type="hidden" id="refreshed" value="no"/>

app/views/shared/_menu.html.erb
<div class="masthead-scrollbar-mask"></div>
<div class="site-navigation" id="site-navigation" aria-hidden="true">
  <nav class="site-navigation--nav" role="navigation">
    <ul class="site-navigation--primary-links">
      <li class="site-navigation--link-container">
        <%= link_to 'Work', work_path, class: "link--underline"%>
      </li>
      

      <li class="site-navigation--link-container">
        <%= link_to 'Insights', insight_path, class: "link--underline"%>
      </li>
      

      <li class="site-navigation--link-container">
        <%= link_to 'Solutions', solution_path, class: "link--underline"%>
      </li>
      

      <li class="site-navigation--link-container">
        <%= link_to 'Company', company_path, class: "link--underline"%>
      </li>
    </ul>
    <ul class="site-navigation--secondary-links">
      <li class="site-navigation--link-container">
        <a class="link--underline" href="news">News</a>
      </li>
      
      <li class="site-navigation--link-container">
        <a class="link--underline" href="careers">Careers</a>
      </li>
    
      <li class="site-navigation--link-container">
        <a class="link--underline" href="contact">Contact</a>
      </li>
    </ul>
  </nav>
</div>